###
# File: fluent-bit.openobserve-http.output.yaml
# Project: fluent-bit
# File Created: Friday, 29th August 2025 2:41:00 pm
# Author: Josh5 (jsunnex@gmail.com)
# -----
# Last Modified: Friday, 29th August 2025 2:41:00 pm
# Modified By: Josh5 (jsunnex@gmail.com)
###

# -- Custom config for OpenObserve http output added here --
